<?php
/**
 * SECTION: gate_scanner — Phase 4 rebuild.
 * 
 * Scans existing ID cards (generated by id_cards.php) to log gate attendance.
 * Also displays visitor QR poster and staff clock-in/out table.
 */
render_breadcrumb(['Dashboard' => 'dashboard.php?section=overview', 'Gate Scanner' => null]);
?>
<!-- SECTION: GATE QR CHECK-IN -->
<?php if ($section === 'gate_scanner'): ?>
    <?php
    $today_gate_logs = [];
    try {
        $lg = $pdo->prepare("SELECT * FROM gate_attendance_logs WHERE school_uuid=? AND DATE(timestamp)=CURDATE() ORDER BY timestamp DESC LIMIT 100");
        $lg->execute([$school_uuid]);
        $today_gate_logs = $lg->fetchAll();
    } catch (Exception $e) {}

    // ── Staff attendance table with date filter ──────────────────────────────
    $sa_date = $_GET['sa_date'] ?? date('Y-m-d');
    $staff_attendance = [];
    try {
        $saq = $pdo->prepare("
            SELECT 
                s.name AS staff_name,
                s.staff_uuid,
                s.role,
                MIN(CASE WHEN g.check_type = 'Check-In' THEN g.timestamp END) AS clock_in,
                MAX(CASE WHEN g.check_type = 'Check-Out' THEN g.timestamp END) AS clock_out,
                COUNT(CASE WHEN g.check_type = 'Check-In' THEN 1 END) AS check_in_count,
                COUNT(CASE WHEN g.check_type = 'Check-Out' THEN 1 END) AS check_out_count
            FROM staff s
            LEFT JOIN gate_attendance_logs g 
                ON g.person_uuid = s.staff_uuid 
                AND g.school_uuid = s.school_uuid
                AND DATE(g.timestamp) = ?
                AND g.status = 'Valid'
            WHERE s.school_uuid = ? AND s.status = 'Active'
            GROUP BY s.staff_uuid, s.name, s.role
            ORDER BY s.name ASC
        ");
        $saq->execute([$sa_date, $school_uuid]);
        $staff_attendance = $saq->fetchAll();
    } catch (Exception $e) {}

    // ── Visitor QR code handling ─────────────────────────────────────────────
    $visitor_kiosk_url = (isset($_SERVER['HTTPS']) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . '/visitor-checkin.php?school=' . urlencode($school_uuid);
    $visitor_qr_url = "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=" . urlencode($visitor_kiosk_url);

    $visitor_logs = [];
    try {
        $vq = $pdo->prepare("SELECT * FROM visitor_logs WHERE school_uuid=? ORDER BY checked_in_at DESC LIMIT 50");
        $vq->execute([$school_uuid]);
        $visitor_logs = $vq->fetchAll();
    } catch (Exception $e) {}
    ?>
    <div class="space-y-6">
        <h1 class="text-xl font-bold text-[var(--text-primary)] flex items-center space-x-2">
            <i data-lucide="scan-line" class="w-6 h-6 text-cyan-400"></i>
            <span>Gate QR Check-In</span>
        </h1>
        <p class="text-xs text-[var(--text-secondary)] -mt-4">
            Scan a student or staff ID card (from the ID Card Designer) to log gate attendance. Visitors scan the poster QR.
        </p>

        <!-- ── Scan panel ────────────────────────────────────────────────────── -->
        <div class="bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl p-6 space-y-4">
            <h3 class="text-sm font-bold text-[var(--text-primary)]">Scan ID Card</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="space-y-2">
                    <video id="gsVideo" class="w-full rounded-xl border border-[var(--border-color)] bg-black aspect-video" muted playsinline></video>
                    <canvas id="gsCanvas" class="hidden"></canvas>
                    <div class="flex gap-2">
                        <button type="button" id="gsStartCam" class="px-3 py-2 bg-cyan-600 hover:bg-cyan-500 text-white text-[10px] font-bold rounded-xl">Start Camera</button>
                        <button type="button" id="gsStopCam" class="px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] text-[var(--text-secondary)] text-[10px] font-bold rounded-xl hidden">Stop Camera</button>
                    </div>
                </div>
                <div class="space-y-2">
                    <div id="gsResult" class="mt-3"></div>
                </div>
            </div>
        </div>

        <!-- ── Visitor Poster with Regenerate Option ──────────────────────────── -->
        <div class="bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl p-6 space-y-4 print:hidden">
            <div class="flex items-center justify-between">
                <h3 class="text-sm font-bold text-[var(--text-primary)]">Visitor Check-In Poster</h3>
                <div class="flex gap-2">
                    <form method="POST" class="inline">
                        <?php echo csrf_field(); ?>
                        <input type="hidden" name="action_regenerate_visitor_qr" value="1">
                        <button type="submit" class="px-3 py-1.5 bg-amber-600 hover:bg-amber-500 text-white text-[10px] font-bold rounded-lg flex items-center gap-1">
                            <i data-lucide="refresh-cw" class="w-3 h-3"></i>
                            Regenerate QR
                        </button>
                    </form>
                    <button onclick="printVisitorPoster()" class="px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white text-xs font-bold rounded-xl flex items-center gap-2">
                        <i data-lucide="printer" class="w-3.5 h-3.5"></i>
                        Print Poster
                    </button>
                </div>
            </div>
            <p class="text-[10px] text-[var(--text-secondary)]">Print and post at the gate. Visitors scan this with their own phone — opens a short form, no login required.</p>
            <div class="text-center">
                <img src="<?php echo $visitor_qr_url; ?>" class="mx-auto rounded-xl border border-[var(--border-color)] bg-white p-2" alt="Visitor Check-In QR">
            </div>
        </div>

        <!-- ── Visitor log ────────────────────────────────────────────────────── -->
        <div class="bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl overflow-hidden print:hidden">
            <div class="p-4 border-b border-[var(--border-color)]"><h3 class="text-sm font-bold text-[var(--text-primary)]">Visitor Log</h3></div>
            <div class="overflow-x-auto">
                <table class="w-full text-xs">
                    <thead class="bg-[var(--bg-tertiary)] text-[var(--text-secondary)] text-[10px] uppercase">
                        <tr><th class="text-left p-3">Name</th><th class="text-left p-3">Phone</th><th class="text-left p-3">Purpose</th><th class="text-left p-3">Host</th><th class="text-left p-3">Time</th></tr>
                    </thead>
                    <tbody class="divide-y divide-[var(--border-color)]">
                        <?php foreach ($visitor_logs as $vl): ?>
                        <tr>
                            <td class="p-3 font-bold text-[var(--text-primary)]"><?php echo htmlspecialchars($vl['name']); ?></td>
                            <td class="p-3 text-[var(--text-secondary)]"><?php echo htmlspecialchars($vl['phone'] ?? ''); ?></td>
                            <td class="p-3 text-[var(--text-secondary)]"><?php echo htmlspecialchars($vl['purpose'] ?? ''); ?></td>
                            <td class="p-3 text-[var(--text-secondary)]"><?php echo htmlspecialchars($vl['host_name'] ?? ''); ?></td>
                            <td class="p-3 text-[var(--text-secondary)]"><?php echo date('M j, g:ia', strtotime($vl['checked_in_at'])); ?></td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if (empty($visitor_logs)): ?><tr><td colspan="5" class="p-4 text-center text-[var(--text-secondary)] italic">No visitors logged yet.</td></tr><?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- ── Staff Attendance Table ────────────────────────────────────────── -->
        <div class="bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl overflow-hidden print:hidden">
            <div class="p-4 border-b border-[var(--border-color)] flex flex-wrap items-center justify-between gap-3">
                <h3 class="text-sm font-bold text-[var(--text-primary)]">Staff Clock-In / Clock-Out</h3>
                <form method="GET" class="flex items-center gap-2">
                    <input type="hidden" name="section" value="gate_scanner">
                    <input type="date" name="sa_date" value="<?php echo htmlspecialchars($sa_date); ?>" onchange="this.form.submit()" class="bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg px-2 py-1 text-xs text-[var(--text-primary)]">
                </form>
            </div>
            <div class="overflow-x-auto">
                <table class="w-full text-xs">
                    <thead class="bg-[var(--bg-tertiary)] text-[var(--text-secondary)] text-[10px] uppercase">
                        <tr>
                            <th class="text-left p-3">Staff</th>
                            <th class="text-left p-3">Role</th>
                            <th class="text-left p-3">Clock In</th>
                            <th class="text-left p-3">Clock Out</th>
                            <th class="text-left p-3">Status</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-[var(--border-color)]">
                        <?php if (empty($staff_attendance)): ?>
                            <tr><td colspan="5" class="p-6 text-center text-[var(--text-secondary)] italic">No staff attendance records for <?php echo htmlspecialchars($sa_date); ?>.</td></tr>
                        <?php else: ?>
                            <?php foreach ($staff_attendance as $sa): 
                                $clock_in = $sa['clock_in'] ? date('H:i', strtotime($sa['clock_in'])) : '—';
                                $clock_out = $sa['clock_out'] ? date('H:i', strtotime($sa['clock_out'])) : '—';
                                $status = ($sa['clock_in'] && $sa['clock_out']) ? 'Complete' : ($sa['clock_in'] ? 'Clocked In' : 'Not Clocked');
                                $statusColor = $status === 'Complete' ? 'text-emerald-400' : ($status === 'Clocked In' ? 'text-amber-400' : 'text-rose-400');
                            ?>
                            <tr>
                                <td class="p-3 font-bold text-[var(--text-primary)]"><?php echo htmlspecialchars($sa['staff_name']); ?></td>
                                <td class="p-3 text-[var(--text-secondary)]"><?php echo htmlspecialchars($sa['role']); ?></td>
                                <td class="p-3 font-mono <?php echo $sa['clock_in'] ? 'text-emerald-400' : 'text-[var(--text-secondary)]'; ?>"><?php echo $clock_in; ?></td>
                                <td class="p-3 font-mono <?php echo $sa['clock_out'] ? 'text-emerald-400' : 'text-[var(--text-secondary)]'; ?>"><?php echo $clock_out; ?></td>
                                <td class="p-3 font-bold <?php echo $statusColor; ?>"><?php echo $status; ?></td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- ── Today's Gate Log ────────────────────────────────────────────────── -->
        <div class="bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl overflow-hidden print:hidden">
            <div class="p-4 border-b border-[var(--border-color)]"><h3 class="text-sm font-bold text-[var(--text-primary)]">Today's Gate Log</h3></div>
            <table class="w-full text-left text-xs">
                <thead class="bg-[var(--bg-tertiary)] text-[var(--text-secondary)] uppercase font-mono text-[10px]">
                    <tr><th class="p-3">Time</th><th class="p-3">Name</th><th class="p-3">Type</th><th class="p-3">Direction</th><th class="p-3">Status</th></tr>
                </thead>
                <tbody class="divide-y divide-[var(--border-color)]" id="gsLogBody">
                    <?php if (empty($today_gate_logs)): ?>
                        <tr><td colspan="5" class="p-6 text-center text-[var(--text-secondary)] italic">No scans logged yet today.</td></tr>
                    <?php else: ?>
                        <?php foreach ($today_gate_logs as $lg): ?>
                        <tr>
                            <td class="p-3 font-mono"><?php echo htmlspecialchars(date('H:i:s', strtotime($lg['timestamp']))); ?></td>
                            <td class="p-3 font-bold"><?php echo htmlspecialchars($lg['person_name']); ?></td>
                            <td class="p-3"><?php echo htmlspecialchars($lg['person_type']); ?></td>
                            <td class="p-3"><?php echo htmlspecialchars($lg['check_type']); ?></td>
                            <td class="p-3">
                                <span class="px-2 py-0.5 rounded text-[10px] font-bold <?php
                                    echo $lg['status']==='Valid' ? 'bg-emerald-500/10 text-emerald-400' : ($lg['status']==='Expired' ? 'bg-amber-500/10 text-amber-400' : 'bg-rose-500/10 text-rose-400');
                                ?>"><?php echo htmlspecialchars($lg['status']); ?></span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>
    <script>
    (function() {
        const video = document.getElementById('gsVideo');
        const canvas = document.getElementById('gsCanvas');
        const ctx = canvas.getContext('2d');
        const startBtn = document.getElementById('gsStartCam');
        const stopBtn = document.getElementById('gsStopCam');
        const resultBox = document.getElementById('gsResult');
        let stream = null, scanning = false, lastCode = '', lastTime = 0;

        function showResult(data) {
            const ok = data.success;
            const color = ok ? 'emerald' : (data.status === 'Expired' ? 'amber' : 'rose');
            resultBox.innerHTML = `<div class="p-3 rounded-xl border text-xs bg-${color}-500/10 border-${color}-500/20 text-${color}-400">
                <strong>${data.person_name || 'Unknown'}</strong> ${data.person_type ? '(' + data.person_type + ')' : ''}<br>
                ${data.check_type ? data.check_type + ' — ' : ''}${data.status || ''} ${data.time ? 'at ' + data.time : ''}<br>
                ${data.error || data.warning || ''}
            </div>`;
        }

        function logCode(code) {
            if (!code) return;
            fetch('api/gate-scan.php', {
                method: 'POST',
                headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                body: 'code=' + encodeURIComponent(code)
            }).then(r => r.json()).then(showResult).catch(() => {
                resultBox.innerHTML = '<div class="p-3 rounded-xl border text-xs bg-rose-500/10 border-rose-500/20 text-rose-400">Network error logging scan.</div>';
            });
        }

        function tick() {
            if (!scanning) return;
            if (video.readyState === video.HAVE_ENOUGH_DATA) {
                canvas.width = video.videoWidth;
                canvas.height = video.videoHeight;
                ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
                const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
                const code = window.jsQR ? jsQR(imageData.data, imageData.width, imageData.height) : null;
                if (code && code.data) {
                    const now = Date.now();
                    if (code.data !== lastCode || now - lastTime > 4000) {
                        lastCode = code.data; lastTime = now;
                        logCode(code.data);
                    }
                }
            }
            requestAnimationFrame(tick);
        }

        startBtn.addEventListener('click', function() {
            navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }).then(function(s) {
                stream = s;
                video.srcObject = stream;
                video.play();
                scanning = true;
                startBtn.classList.add('hidden');
                stopBtn.classList.remove('hidden');
                requestAnimationFrame(tick);
            }).catch(function() {
                resultBox.innerHTML = '<div class="p-3 rounded-xl border text-xs bg-rose-500/10 border-rose-500/20 text-rose-400">Could not access camera — use manual entry instead.</div>';
            });
        });
        stopBtn.addEventListener('click', function() {
            scanning = false;
            if (stream) stream.getTracks().forEach(t => t.stop());
            stopBtn.classList.add('hidden');
            startBtn.classList.remove('hidden');
        });
    })();

    function printVisitorPoster() {
    const qrUrl = "<?php echo $visitor_qr_url; ?>";
    const schoolName = "<?php echo htmlspecialchars($school['name'] ?? 'School'); ?>";
    
    // Build a clean A4 page with just the QR code
    const win = window.open('', '_blank');
    win.document.write(`
        <html>
        <head>
            <title>Visitor Check-In QR — ${schoolName}</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body {
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    justify-content: center;
                    min-height: 100vh;
                    background: white;
                    font-family: Arial, sans-serif;
                    padding: 40px;
                }
                .container {
                    text-align: center;
                    max-width: 600px;
                    width: 100%;
                }
                .qr-img {
                    max-width: 300px;
                    width: 100%;
                    height: auto;
                    border: 2px solid #ddd;
                    border-radius: 12px;
                    padding: 12px;
                    background: white;
                    margin: 20px auto;
                }
                h1 {
                    font-size: 24px;
                    color: #1a1a1a;
                    margin-bottom: 8px;
                }
                p {
                    font-size: 14px;
                    color: #555;
                    margin-bottom: 20px;
                }
                .footer {
                    font-size: 12px;
                    color: #999;
                    margin-top: 40px;
                    border-top: 1px solid #eee;
                    padding-top: 20px;
                }
                @media print {
                    body { padding: 20px; }
                    .qr-img { max-width: 250px; }
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>${schoolName}</h1>
                <p>Scan this QR code with your phone to check in as a visitor.</p>
                <img src="${qrUrl}" class="qr-img" alt="Visitor Check-In QR">
                <div class="footer">
                    Powered by Zetaphase EduCloud &bull; ${new Date().toLocaleDateString()}
                </div>
            </div>
            <script>
                window.onload = function() {
                    window.print();
                };
            </scr` + `ipt>
        </body>
        </html>
    `);
    win.document.close();
}
    </script>
<?php endif; ?>